---
name: Deploy to DigitalOcean
on:
  push:
    branches:
      - production
jobs:
  deploy-production:
    if: github.ref == 'refs/heads/production'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run production
      - name: Deploy app to DigitalOcean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          rm: true
          source: "dist/backoffice-frontend/"
          target: ${{ secrets.TARGET_PROD }}
      - name: Restart Apache2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: sudo systemctl restart apache2
